inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'lib/**/*'
    - 'config.ru'
    - 'spec/**/*'
    - 'bin/**/*'
    - 'app/channels/**/*'
    - 'app/jobs/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'node_modules/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
  StyleGuideCopsOnly:
    FrozenStringLiteralComment:
      Enabled: false