inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'config/environments/**/*'
    - 'config/initializers/assets.rb'
    - 'config/boot.rb'
    - 'spec/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'node_modules/**/*'
  StyleGuideCopsOnly:
    FrozenStringLiteralComment:
      Enabled: false